import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { Song } from '../src/models/song.model.js';
import { Playlist, serializePlaylist } from '../src/models/playlist.model.js';
import { SearchHistory } from '../src/models/search-history.model.js';
import { createPlaylist, addSongs, songInputs } from '../src/services/playlist.service.js';
import { resolveSong } from '../src/services/song-identity.service.js';
import { reserveHistory, finishHistory } from '../src/services/search-history.service.js';
let mongo;
before(async () => { mongo = await MongoMemoryServer.create(); await mongoose.connect(mongo.getUri()); await Promise.all([Song.init(), Playlist.init(), SearchHistory.init()]); });
after(async () => { await mongoose.disconnect(); await mongo.stop(); });
test('playlist/history share canonical reference but preserve entry IDs and never copy content', async () => {
    const input = { title: 'Own synthetic', artist: 'Fixture', originType: 'identified' }, owner = new mongoose.Types.ObjectId();
    const global = await resolveSong(input);
    const { doc } = await createPlaylist(owner, { name: 'Fixture', songs: [input] });
    const dto = serializePlaylist(doc);
    assert.equal(String(dto.songs[0].songId), String(global._id));
    assert.notEqual(dto.songs[0].id, String(global._id));
    const again = await addSongs(owner, doc.id, songInputs([{ ...input, songId: String(global._id) }]));
    assert.equal(again.addedCount, 0); assert.equal(again.doc.songs[0].id, dto.songs[0].id);
    const { doc: history } = await reserveHistory(owner, 'synthetic-request', {});
    await finishHistory(history, { input: {}, result: { found: true, song: { ...input, songId: global._id, lyrics: 'forbidden copy' }, recommendations: [] } });
    const snapshot = await SearchHistory.findById(history._id).lean();
    assert.equal(String(snapshot.result.song.songId), String(global._id));
    assert.ok(!JSON.stringify(snapshot).includes('forbidden copy'));
    await SearchHistory.deleteOne({ _id: history._id }); assert.ok(await Song.findById(global._id));
    await assert.rejects(createPlaylist(owner, { name: 'Wrong ID', songs: [{ ...input, title: 'Another', songId: String(global._id) }] }), { code: 'SONG_IDENTITY_MISMATCH' });
    assert.equal(await Playlist.countDocuments(), 1);
    assert.equal(await Song.countDocuments({ 'lyrics.lookupAttempted': true }), 0);
    const edition = await addSongs(owner, doc.id, songInputs([{ ...input, edition: 'live' }]));
    assert.equal(edition.addedCount, 1); assert.equal(edition.doc.songs.length, 2);
    assert.notEqual(String(edition.doc.songs[0].songId), String(edition.doc.songs[1].songId));
});
